In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
sns.set()

In [2]:
raw_data = pd.read_csv('2.01. Admittance.csv')
raw_data.head()

SAT Admitted
0  1363       No
1  1792      Yes
2  1954      Yes
3  1653       No
4  1593       No

In [3]:
data = raw_data.copy()
data['Admitted'] = data['Admitted'].map({'Yes':1,'No':0})
data.head()

SAT  Admitted
0  1363         0
1  1792         1
2  1954         1
3  1653         0
4  1593         0

In [5]:
y = data['Admitted']
x1 = data['SAT']

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,y,test_size=0.1)

In [43]:
x_train_matrix = x_train.values.reshape(-1,1)

In [44]:
reg = LogisticRegression()
reg.fit(x_train_matrix,y_train)

LogisticRegression()

In [45]:
reg.intercept_

array([-71.14006252])

In [46]:
reg.coef_

array([[0.04279118]])

## Confusion matrix on sklearn

In [47]:
y_predict = reg.predict(x_train_matrix)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train,y_predict)
cm_df = pd.DataFrame(cm)
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df.index = ['Actual 0','Actual 1']
cm_df

Predicted 0  Predicted 1
Actual 0           61            7
Actual 1            5           78

In [48]:
accuracy_train = (cm[0,0]+cm[1,1])/cm.sum()
accuracy_train

0.9205298013245033

In [49]:
cm

array([[61,  7],
       [ 5, 78]], dtype=int64)

In [51]:
SAT = int(input())
yhat = reg.intercept_+reg.coef_*SAT
p = 1/(1+np.exp(-yhat))
if p>0.5:
    print('Probability:',(p*100))
    print('1')
else:
    print('Probability:',p*100)
    print('0')
    

1699
Probability: [[82.66631881]]
1


### Test the model

In [52]:
x_test_matrix = x_test.values.reshape(-1,1)
y_predict_test = reg.predict(x_test_matrix)

In [53]:
cm_test = confusion_matrix(y_test,y_predict_test)
cm_df_test = pd.DataFrame(cm_test)
cm_df_test.columns = ['Predicted 0','Predicted 1']
cm_df_test.index = ['Actual 0','Actual 1']
cm_df_test

Predicted 0  Predicted 1
Actual 0            5            1
Actual 1            0           11

In [54]:
accuracy_train = (cm_test[0,0]+cm_test[1,1])/cm_test.sum()
accuracy_train

0.9411764705882353

In [55]:
reg.score(x_test_matrix,y_test)

0.9411764705882353