In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
sns.set()

In [2]:
raw_data = pd.read_csv('2.02. Binary predictors.csv')
raw_data.head()

SAT Admitted  Gender
0  1363       No    Male
1  1792      Yes  Female
2  1954      Yes  Female
3  1653       No    Male
4  1593       No    Male

In [4]:
data = raw_data.copy()
data['Admitted'] = data['Admitted'].map({'Yes':1,'No':0})
data['Gender'] = data['Gender'].map({'Female':1,'Male':0})
data.head()

SAT  Admitted  Gender
0  1363         0       0
1  1792         1       1
2  1954         1       1
3  1653         0       0
4  1593         0       0

In [5]:
y = data['Admitted']
x1 = data['Gender']

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,y,test_size=0.1)

In [7]:
x_train_matrix = x_train.values.reshape(-1,1)

In [8]:
reg = LogisticRegression()
reg.fit(x_train_matrix,y_train)

LogisticRegression()

In [9]:
reg.intercept_

array([-0.57411572])

In [10]:
reg.coef_

array([[1.82318539]])

## Confusion matrix on sklearn

In [11]:
y_predict = reg.predict(x_train_matrix)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train,y_predict)
cm_df = pd.DataFrame(cm)
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df.index = ['Actual 0','Actual 1']
cm_df

Predicted 0  Predicted 1
Actual 0           53           14
Actual 1           27           57

In [12]:
accuracy_train = (cm[0,0]+cm[1,1])/cm.sum()
accuracy_train

0.7284768211920529

In [13]:
cm

array([[53, 14],
       [27, 57]], dtype=int64)

In [14]:
f = 1
m = 0
result = (np.exp(reg.coef_)*(f-m)).round(2)
print('The odds of female to get admitted is {} times greater than the odds of males to get admitted in this dataset'.format(result))
    

The odds of female to get admitted is [[6.19]] times greater than the odds of males to get admitted in this dataset


### Test the model

In [15]:
x_test_matrix = x_test.values.reshape(-1,1)
y_predict_test = reg.predict(x_test_matrix)

In [16]:
cm_test = confusion_matrix(y_test,y_predict_test)
cm_df_test = pd.DataFrame(cm_test)
cm_df_test.columns = ['Predicted 0','Predicted 1']
cm_df_test.index = ['Actual 0','Actual 1']
cm_df_test

Predicted 0  Predicted 1
Actual 0            6            1
Actual 1            4            6

In [17]:
accuracy_train = (cm_test[0,0]+cm_test[1,1])/cm_test.sum()
accuracy_train

0.7058823529411765

In [18]:
reg.score(x_test_matrix,y_test)

0.7058823529411765